### ISSUE TITLE
Feedparser AttributeError in Python 3.9

### ISSUE THREAD

**Issue by apmarshall** [donnemartin/gitsome#186]
Python 3.9 makes a change in how `base64.decodestring` works, which in particular impacts Gitsome's use of feedparser. See [this issue](https://github.com/kurtmckee/feedparser/issues/201) for more information. This was fixed in later versions of feedparser, so gitsome needs to allow those later version to work on Python 3.9.

Pull request to address this forthcoming.

**Comment by kwanhur** [comment]
Any update on this issue?

I caught `base64.decodestring` related problem at version 0.8.4, located at `main_cli.py` as beblow

```shell
➜ gitsome
Gitsome Version: 0.8.4


kwanhur at C02P57TSG3QJ in ~ on
$ gh configure
Traceback (most recent call last):
  File "/usr/local/bin/gh", line 5, in <module>
    from gitsome.main_cli import cli
  File "/usr/local/lib/python3.9/site-packages/gitsome/main_cli.py", line 20, in <module>
    from .githubcli import GitHubCli
  File "/usr/local/lib/python3.9/site-packages/gitsome/githubcli.py", line 21, in <module>
    from .github import GitHub
  File "/usr/local/lib/python3.9/site-packages/gitsome/github.py", line 29, in <module>
    import feedparser
  File "/usr/local/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```
